[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."cron-hourly"]
  schedule = "@hourly"

[functions."cron-daily"]
  schedule = "0 4 * * *"

[build]
  publish = "public"
  command = "echo 'No DB build needed for Google Sheets'"
